### ISSUE TITLE
Out of date dependencies

### ISSUE THREAD

**Issue by modem7** [omegion/ssh-manager#12]
**Describe the bug**
Several dependencies are out of date

**Additional context**
May be worthwhile implementing dependabot to automate updates. 

```
version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
```
